# Generated by Django 5.2 on 2026-02-05 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_code', models.CharField(max_length=20, unique=True, verbose_name='法人コード')),
                ('name', models.CharField(max_length=255, verbose_name='法人名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
            ],
            options={
                'verbose_name': '1. 法人',
                'verbose_name_plural': '1. 法人管理',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record_date', models.DateField(verbose_name='記録日')),
                ('wakeup_time', models.TimeField(blank=True, null=True, verbose_name='起床時刻')),
                ('sleep_time', models.TimeField(blank=True, null=True, verbose_name='就寝時刻')),
            ],
            options={
                'verbose_name': '日次記録',
                'verbose_name_plural': '7. サービス実施記録',
                'db_table': 'daily_record',
            },
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident_code', models.CharField(max_length=20, unique=True, verbose_name='利用者コード')),
                ('name', models.CharField(max_length=255, verbose_name='利用者名')),
                ('birth_date', models.DateField(verbose_name='生年月日')),
                ('care_level', models.IntegerField(default=1, verbose_name='要介護度')),
                ('room_number', models.CharField(blank=True, max_length=20, verbose_name='居室番号')),
                ('diagnosis', models.TextField(blank=True, verbose_name='既往歴・持病')),
                ('emergency_contact', models.TextField(blank=True, verbose_name='緊急連絡先')),
                ('notes', models.TextField(blank=True, verbose_name='特記事項')),
            ],
            options={
                'verbose_name': '3. 利用者',
                'verbose_name_plural': '3. 利用者マスタ',
                'db_table': 'resident',
            },
        ),
        migrations.CreateModel(
            name='DailyRecordItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_goal_no', models.PositiveIntegerField(blank=True, help_text='計画書の「目標番号」を入力', null=True, verbose_name='対象目標番号')),
                ('item_value', models.TextField(verbose_name='実施内容・結果')),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='体温')),
                ('blood_pressure_high', models.IntegerField(blank=True, null=True, verbose_name='血圧(高)')),
                ('blood_pressure_low', models.IntegerField(blank=True, null=True, verbose_name='血圧(低)')),
                ('pulse', models.IntegerField(blank=True, null=True, verbose_name='脈拍')),
                ('daily_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='group_home.dailyrecord')),
            ],
            options={
                'verbose_name': '実施詳細',
                'verbose_name_plural': '実施詳細',
                'db_table': 'daily_record_item',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office_code', models.CharField(max_length=20, unique=True, verbose_name='事業所コード')),
                ('name', models.CharField(max_length=255, verbose_name='事業所名')),
                ('opened_on', models.DateField(verbose_name='開設日')),
                ('closed_on', models.DateField(blank=True, null=True, verbose_name='廃止日')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offices', to='group_home.company')),
            ],
            options={
                'verbose_name': '2. 事業所',
                'verbose_name_plural': '2. 事業所管理',
                'db_table': 'office',
            },
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group_home.office', verbose_name='事業所'),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='group_home.resident', verbose_name='利用者'),
        ),
        migrations.CreateModel(
            name='ResidentOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='利用開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='利用終了日')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='group_home.office', verbose_name='事業所')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='group_home.resident', verbose_name='利用者')),
            ],
            options={
                'verbose_name': '利用者在籍履歴',
                'verbose_name_plural': '4. 利用者在籍・契約管理',
                'db_table': 'resident_office',
            },
        ),
        migrations.CreateModel(
            name='SupportPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_plans', to='group_home.resident')),
            ],
            options={
                'verbose_name': '個別支援計画マスタ',
                'verbose_name_plural': '5. 個別支援計画マスタ',
                'db_table': 'support_plan',
            },
        ),
        migrations.CreateModel(
            name='SupportPlanRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_no', models.PositiveIntegerField(verbose_name='リビジョン番号')),
                ('plan_start_date', models.DateField(verbose_name='計画開始日')),
                ('plan_end_date', models.DateField(verbose_name='計画終了日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('support_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_home.supportplan', verbose_name='個別支援計画')),
            ],
            options={
                'verbose_name': '支援計画書（更新履歴）',
                'verbose_name_plural': '6. 支援計画書（更新履歴）',
                'db_table': 'support_plan_revision',
                'unique_together': {('support_plan', 'revision_no')},
            },
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_goal_no', models.PositiveIntegerField(verbose_name='対象目標番号')),
                ('monitoring_date', models.DateField(verbose_name='モニタリング実施日')),
                ('long_term_goal_snapshot', models.TextField(blank=True, null=True, verbose_name='当時の長期目標')),
                ('short_term_goal_snapshot', models.TextField(blank=True, null=True, verbose_name='当時の短期目標')),
                ('achievement_status', models.CharField(choices=[('A', '達成（継続）'), ('B', '一部達成（内容変更）'), ('C', '未達成（計画見直し）'), ('D', '目標消滅')], max_length=1, verbose_name='進捗評価')),
                ('comment', models.TextField(verbose_name='評価コメント・特記事項')),
                ('support_plan_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitorings', to='group_home.supportplanrevision', verbose_name='対象計画リビジョン')),
            ],
            options={
                'verbose_name': 'モニタリング',
                'verbose_name_plural': 'モニタリング',
                'db_table': 'monitoring',
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('resident', 'record_date')},
        ),
        migrations.CreateModel(
            name='SupportPlanGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal_no', models.PositiveIntegerField(verbose_name='目標番号')),
                ('goal_text', models.TextField(verbose_name='目標内容')),
                ('support_plan_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goals', to='group_home.supportplanrevision')),
            ],
            options={
                'verbose_name': '支援計画',
                'verbose_name_plural': '5. 支援計画（基本）',
                'db_table': 'support_plan_goal',
                'unique_together': {('support_plan_revision', 'goal_no')},
            },
        ),
        migrations.CreateModel(
            name='SupportPlanContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_no', models.PositiveIntegerField(verbose_name='支援内容番号')),
                ('content_text', models.TextField(verbose_name='支援内容')),
                ('related_goal_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='対応目標番号')),
                ('support_plan_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='group_home.supportplanrevision')),
            ],
            options={
                'verbose_name': '計画リビジョン',
                'verbose_name_plural': '6. 計画作成・更新履歴',
                'db_table': 'support_plan_content',
                'unique_together': {('support_plan_revision', 'content_no')},
            },
        ),
    ]
